BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS 'words' (
    word_id INTEGER PRIMARY KEY AUTOINCREMENT,
    text TEXT NOT NULL,
    type_id INTEGER NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
    FOREIGN KEY(type_id) REFERENCES types(type_id)
);

CREATE UNIQUE INDEX words_text_type_id_index ON words (text, type_id);

CREATE TRIGGER update_words_updated_at AFTER UPDATE ON words
BEGIN
    UPDATE words
    SET updated_at = datetime('now', 'localtime')
    WHERE word_id = NEW.word_id;
END;

CREATE TABLE IF NOT EXISTS 'types' (
    type_id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now', 'localtime'))
);

CREATE UNIQUE INDEX types_name_index ON types (name);

CREATE TRIGGER update_types_updated_at AFTER UPDATE ON types
BEGIN
    UPDATE types
    SET updated_at = datetime('now', 'localtime')
    WHERE type_id = NEW.type_id;
END;

INSERT INTO types
    (type_id, name)
VALUES
    (1, "spice"),
    (2, "wyrd");

INSERT INTO words
    (type_id, text)
VALUES
    (1, "ache"),
    (1, "aching longing"),
    (1, "all-consuming"),
    (1, "all-encompassing love"),
    (1, "bare"),
    (1, "beneath the skin"),
    (1, "body jolting"),
    (1, "body screaming"),
    (1, "body thrumming"),
    (1, "breaking"),
    (1, "breath"),
    (1, "breath catching"),
    (1, "breath caught in the throat"),
    (1, "breathing in each other's scent"),
    (1, "breathing raggedly"),
    (1, "breathless"),
    (1, "breathtaking"),
    (1, "burning through"),
    (1, "caress"),
    (1, "chest rising and falling"),
    (1, "climaxing"),
    (1, "cling"),
    (1, "closeness"),
    (1, "clutching"),
    (1, "collapsing"),
    (1, "collapsing into"),
    (1, "complete surrender"),
    (1, "consumed"),
    (1, "cracking wide open"),
    (1, "crashing together"),
    (1, "cresting"),
    (1, "crushing desire"),
    (1, "dazzling"),
    (1, "desire"),
    (1, "desperate yearning"),
    (1, "devouring"),
    (1, "drawn toward"),
    (1, "electric"),
    (1, "embrace"),
    (1, "enraptured"),
    (1, "entangled"),
    (1, "entwine"),
    (1, "entwined"),
    (1, "exploding"),
    (1, "explosive"),
    (1, "eyes glowing"),
    (1, "feeling whole"),
    (1, "fervent"),
    (1, "fever"),
    (1, "fevered"),
    (1, "feverish"),
    (1, "fill"),
    (1, "filling up"),
    (1, "final release"),
    (1, "finger"),
    (1, "fingers digging in"),
    (1, "fingers lingering"),
    (1, "fire"),
    (1, "flame"),
    (1, "flesh"),
    (1, "flickering gaze"),
    (1, "flushed"),
    (1, "flushed cheeks"),
    (1, "fluttering heart"),
    (1, "frantic"),
    (1, "fulfilling"),
    (1, "furious ache"),
    (1, "gasp"),
    (1, "gasping"),
    (1, "gentle press"),
    (1, "grasp"),
    (1, "grasping"),
    (1, "grip"),
    (1, "gripping"),
    (1, "gripping each other tight"),
    (1, "guttural cry"),
    (1, "hands traveling"),
    (1, "heartbeat"),
    (1, "heartbreaking"),
    (1, "heart pounding against chest"),
    (1, "heart racing"),
    (1, "heat"),
    (1, "heat building"),
    (1, "heat burning between them"),
    (1, "heat radiating"),
    (1, "heatwave"),
    (1, "hot breath"),
    (1, "hot skin beneath"),
    (1, "hunger"),
    (1, "inescapable pull"),
    (1, "inhaling each other"),
    (1, "intense eye contact"),
    (1, "intense wave"),
    (1, "intensity"),
    (1, "intoxicating"),
    (1, "kiss"),
    (1, "languid"),
    (1, "legs tangling"),
    (1, "limp with satisfaction"),
    (1, "linger"),
    (1, "lips"),
    (1, "lips brushing"),
    (1, "lips curving"),
    (1, "lips parting"),
    (1, "locked together"),
    (1, "longing"),
    (1, "losing control"),
    (1, "lost in sensation"),
    (1, "lust"),
    (1, "lust-darkened eyes"),
    (1, "lustful"),
    (1, "magnetic"),
    (1, "mind-shattering"),
    (1, "moan"),
    (1, "mouth on skin"),
    (1, "mouth watering"),
    (1, "nip"),
    (1, "obsession"),
    (1, "overcome"),
    (1, "overflowing"),
    (1, "overwhelming"),
    (1, "passion"),
    (1, "pressed together"),
    (1, "pulling closer"),
    (1, "pulse"),
    (1, "pulsing"),
    (1, "pure bliss"),
    (1, "pushing past the edge"),
    (1, "raging need"),
    (1, "rapture"),
    (1, "ravishing"),
    (1, "releasing everything"),
    (1, "savoring"),
    (1, "screaming"),
    (1, "screaming out"),
    (1, "searing"),
    (1, "seduce"),
    (1, "seduction"),
    (1, "seductive"),
    (1, "sensation"),
    (1, "shaking"),
    (1, "sharp intake of breath"),
    (1, "shiver"),
    (1, "shivering with need"),
    (1, "shudder"),
    (1, "shuddering"),
    (1, "sigh"),
    (1, "silken"),
    (1, "silken skin"),
    (1, "sin"),
    (1, "sinking deeper"),
    (1, "sinking into"),
    (1, "slick"),
    (1, "slow burn"),
    (1, "smoldering"),
    (1, "smothered sighs"),
    (1, "soft"),
    (1, "soft moans"),
    (1, "spark"),
    (1, "steamy"),
    (1, "sudden rush"),
    (1, "sultry look"),
    (1, "surrender"),
    (1, "surrendering"),
    (1, "swallowed gasp"),
    (1, "sweat slicked"),
    (1, "sweat-slicked bodies"),
    (1, "sweltering"),
    (1, "tangle"),
    (1, "tangled"),
    (1, "tantalizing"),
    (1, "tearing through"),
    (1, "tears of release"),
    (1, "tease"),
    (1, "teasing"),
    (1, "teasing touch"),
    (1, "temptation"),
    (1, "tense"),
    (1, "tension"),
    (1, "tension building"),
    (1, "tension snapping"),
    (1, "thirsty"),
    (1, "throb"),
    (1, "throbbing"),
    (1, "thrumming pulse"),
    (1, "thrust"),
    (1, "tightening"),
    (1, "tingling"),
    (1, "tongue tracing"),
    (1, "touch"),
    (1, "trembling"),
    (1, "tug"),
    (1, "unbearable"),
    (1, "uncontrollable"),
    (1, "undone"),
    (1, "unleashed"),
    (1, "unraveling"),
    (1, "voice breaking"),
    (1, "whisper"),
    (1, "wicked desire"),
    (1, "wild"),
    (1, "wild longing"),
    (1, "wrapped in"),
    (1, "writhing"),
    (1, "yearning"),
    (2, "armor"),
    (2, "battle"),
    (2, "blood"),
    (2, "cast"),
    (2, "castle"),
    (2, "crown"),
    (2, "curse"),
    (2, "dagger"),
    (2, "dark"),
    (2, "destiny"),
    (2, "dragon"),
    (2, "dream"),
    (2, "embrace"),
    (2, "enchantment"),
    (2, "fate"),
    (2, "fire"),
    (2, "forbidden"),
    (2, "forest"),
    (2, "glimmer"),
    (2, "greave"),
    (2, "heart"),
    (2, "helmet"),
    (2, "kingdom"),
    (2, "knight"),
    (2, "light"),
    (2, "love"),
    (2, "magic"),
    (2, "magic-wielder"),
    (2, "midnight"),
    (2, "moon"),
    (2, "power"),
    (2, "prince"),
    (2, "princess"),
    (2, "promise"),
    (2, "prophecy"),
    (2, "realm"),
    (2, "ritual"),
    (2, "secret"),
    (2, "shadow"),
    (2, "sorcery"),
    (2, "soulmate"),
    (2, "spell"),
    (2, "storm"),
    (2, "sword"),
    (2, "tear"),
    (2, "thief"),
    (2, "thorn"),
    (2, "truth"),
    (2, "vampire"),
    (2, "warlock"),
    (2, "witch"),
    (2, "witchcraft"),
    (2, "wizard"),
    (2, "wolf");

COMMIT;
